name: Backend checks

on:
  push:
    branches:
      - main
    paths:
      - 'services/**'
      - '.github/workflows/backend.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'services/**'
      - '.github/workflows/backend.yml'

jobs:
  services-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
        docker build -t services-app -f services/despesapp.Dockerfile ./services
